[package]
name = "raw-echo-tcp-server"
version = "0.1.0"
edition = "2021"
authors = ["M.Amin Rayej <m.amin.rayej@gmail.com>"]
license = "MIT"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
